services:
  - type: web
    name: mega-link-downloader-bot
    env: python
    region: oregon   # or frankfurt, singapore, etc.
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    disk:
      name: data
      mountPath: /data
      sizeGB: 10
    envVars:
  - key: API_ID
    value: "23990433"
  - key: API_HASH
    value: "e6c4b6ee1933711bc4da9d7d17e1eb20"
  - key: BOT_TOKEN
    value: "7972560151:AAHlUN7BOsfPwu-LFUpuAV0YLqyGdkEXsrU"
  - key: MEGA_EMAIL
    value: "youtu0323@gmail.com"
  - key: MEGA_PASSWORD
    value: "12345678Sa@#$"
